-- VISTA DEL REPORTE APS
CREATE VIEW v_programacion_aps
AS
SELECT
    CONCAT(P.NOMBRE, ' ', P.PATERNO, ' ', P.MATERNO) AS PERSONAL,
    RD.FECHA, RC.ESTABLECIMIENTO, RC.CONDICION,
    CASE
        WHEN RD.H_INGRESO IS NULL AND RD.H_SALIDA IS NULL THEN 'NO REALIZÓ'
        ELSE 'SI REALIZÓ'
    END AS Status,
	
FROM
    dbo.PERSONAL AS P
INNER JOIN
    dbo.ROLC AS RC ON P.ID = RC.PERSONAL
INNER JOIN
    dbo.ROLD AS RD ON RC.ID = RD.ID_CABECERA
WHERE
    H_P_ACTUAL IN ('85', '91', '92', '93','94','111','112','113','114') AND RC.CONDICION = 'CAS REGULAR' AND RC.ESTABLECIMIENTO = 'CENTRO MATERNO INFANTIL DR. ENRIQUE MARTIN ALTUNA';
GO
--*****************************
--PROCEDOMIENTO ALMACENADO DEL REPORTE APS
CREATE PROCEDURE APS
    @Establecimiento VARCHAR(255),
    @Fecha1 DATE = NULL, 
    @Fecha2 DATE = NULL,     
	@Planilla INT

AS
BEGIN
    SELECT
        CONCAT(P.NOMBRE, ' ', P.PATERNO, ' ', P.MATERNO) AS PERSONAL,
        RC.ESTABLECIMIENTO,
		RD.FECHA, RD.H_INGRESO, RD.H_SALIDA,
        CASE
            WHEN RD.H_INGRESO IS NULL AND RD.H_SALIDA IS NULL THEN 'NO REALIZÓ'
            ELSE 'SI REALIZÓ'
        END AS Status
    FROM
        dbo.PERSONAL AS P
    INNER JOIN
        dbo.ROLC AS RC ON P.ID = RC.PERSONAL
    INNER JOIN
        dbo.ROLD AS RD ON RC.ID = RD.ID_CABECERA
    WHERE
			H_P_ACTUAL IN ('85', '91', '92', '93','94','111','112','113','114')
        AND RC.ESTABLECIMIENTO = @Establecimiento
		AND RD.FECHA BETWEEN @Fecha1 AND @Fecha2
		AND P.TIPO_PLANILLA = @Planilla
ORDER BY
P.PATERNO,
P.MATERNO,
P.NOMBRE,
RC.ESTABLECIMIENTO,
RD.FECHA;
END
GO
--PRUEBAS
EXEC APS 
    @Establecimiento = 'CENTRO MATERNO INFANTIL DR. ENRIQUE MARTIN ALTUNA', 
    @Fecha1 = '2025-01-01', 
    @Fecha2 = '2025-11-30', 
	@Planilla = 8;
GO
